<?php
    /**
     * @var  $block WeSupply\Toolbox\Block\Notification
     */
    // all country codes and their phone prefix
    $phonePrefixes = $block->getCountryPhoneCodes();
    // order data
    $orderId = $block->getUnsubscribeFlag() ? '' : $block->getWesupplyExternalOrderId();
    $orderPhone = $block->getShippingPhone();
    $orderCountryCode = $block->getShippingCountryCode();
    // other settings
    $orderIdFieldType = $block->getUnsubscribeFlag() ? 'text' : 'hidden';
    $buttonTitle = $block->getUnsubscribeFlag() ? __('Unsubscribe') : __('Subscribe');
    $descriptionText = $block->getUnsubscribeFlag() ? __('Unsubscribe from receiving updates via SMS') : __('Subscribe to receive updates via SMS');
    $successMessage = $block->getUnsubscribeFlag() ? __('Success! From now on you will not receive any notification!') : __('Success! You will receive a notification once your order is updated!')
?>
<?php if ($block->getEnabledNotification() && $block->getNotificationBoxType() == $block->getDefaultLocationType()): ?>
    <?php if ($block->getDesign() == $block->getFirstDesignConstant()): ?>
        <?php $centeredClass = $block->getAlignment() == $block->getCenterAlignmentConstant() ? 'sms-center' : ''; ?>
        <div id="ws_embed_sms_notification" class="ws-left design-1 <?php echo $centeredClass; ?>">
            <h2><?php /* @escapeNotVerified */ echo __('SMS NOTIFICATION') ?></h2>
            <span class="block-span mg-top-span">
                <?php /* @escapeNotVerified */ echo __($descriptionText) ?>
            </span>
            <form id="ws-embedded-sms-notification-form" name="ws-embedded-sms-notification-form" autocomplete="off">
                <div class="ws-field-group">
                    <input type="<?php echo $orderIdFieldType; ?>"  name="orderId" id="ws-orderId" value="<?php echo $orderId ?>" placeholder="Order Number" required/>
                </div>
                <div class="ws-field-group control-subs">
                    <?php if (is_array($phonePrefixes)): ?>
                        <select name="phonePrefix" id="phonePrefix" class="ws-Phone ws-country-pc">
                            <?php foreach ($phonePrefixes AS $countryCode => $data): ?>
                                <option data-country-code="<?php echo $countryCode ?>" <?php echo $orderCountryCode == $countryCode ? 'selected="selected"' : ''; ?> value="<?php echo $data['code'] ?>">
                                    <?php echo $countryCode . ' (' . $data['code'] . ') ';  ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                    <input type="hidden" name="countryCode" id="countryCode" value="<?php echo $orderCountryCode ?>" />
                    <input type="text" name="phone" id="ws-Phone" class="ws-Phone" value="<?php echo $orderPhone; ?>" autocomplete="off">
                    <button class="action subscribe primary sms-subs" title="Subscribe" id="ws-embedded-subscribe">
                        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
                    </button>
                </div>
            </form>
        </div>
        <div id="ws-responses" class="<?php echo $centeredClass ?>">
            <div class="ws_error" id="ws-error-response" style="display:none"></div>
            <div class="ws_success" id="ws-success-response" style="display:none"><?php /* @escapeNotVerified */ echo __($successMessage) ?></div>
        </div>
    <?php else: ?>
        <?php $centeredClass = $block->getAlignment() == $block->getCenterAlignmentConstant() ? 'sms-center-design-2' : ''; ?>
        <div id="ws_embed_sms_notification" class="ws_embed_sms_notification <?php echo $centeredClass; ?>">
            <div class="inline-block">
                <div class="ws-title-description-container-dsg2">
                    <h2 class="title-dsg-2"><?php /* @escapeNotVerified */ echo __('GET SMS UPDATES') ?></h2>
                    <span class="description-dsg-2">
                        <?php /* @escapeNotVerified */ echo __($descriptionText) ?>
                    </span>
                </div>
                <form id="ws-embedded-sms-notification-form" class="ws-embedded-sms-notification-form-dsg-2" name="ws-embedded-sms-notification-form" autocomplete="off">
                    <div class="ws-field-group">
                        <input class="ws-orderId-dsg2" type="<?php echo $orderIdFieldType; ?>"  name="orderId" id="ws-orderId" value="<?php echo $orderId ?>" placeholder="Order Number" required/>
                    </div>
                    <div class="ws-field-group control-subs-2">
                        <?php if (is_array($phonePrefixes)): ?>
                            <select class="ws-phone-dsg-2 ws-country-pc-dsg2" id="phonePrefix" name="phonePrefix">
                                <?php foreach ($phonePrefixes AS $countryCode => $data): ?>
                                    <option data-country-code="<?php echo $countryCode ?>" <?php echo $orderCountryCode == $countryCode ? 'selected = "selected"' : ''; ?> value="<?php echo $data['code'] ?>">
                                        <?php echo $countryCode . ' (' . $data['code'] . ') '; ?>
                                    </option>
                                <?php endforeach ?>
                            </select>
                        <?php endif; ?>
                        <input type="hidden" name="countryCode" id="countryCode" value="<?php echo $orderCountryCode ?>" />
                        <input type="text" name="phone" id="ws-Phone" class="ws-phone-dsg-2" value="<?php echo $orderPhone; ?>" autocomplete="off">
                        <button class="action subscribe primary sms-subs" title="Sign Up" id="ws-embedded-subscribe">
                            <span><?php echo __($buttonTitle) ?></span>
                        </button>
                    </div>
                </form>
            </div>
            <div id="ws-responses" class="ws-responses  <?php echo $centeredClass; ?>">
                <div class="ws_error" id="ws-error-response" style="display:none"></div>
                <div class="ws_success" id="ws-success-response" style="display:none"><?php /* @escapeNotVerified */ echo __($successMessage) ?></div>
            </div>
        </div>
    <?php endif; ?>

    <script>
        require(['jquery'], function ($) {
            $(document).ready(function () {
                $('#phonePrefix').on('change', function() {
                    $('#countryCode').val($(this).find(':selected').data('country-code'));
                });
                $("#ws-embedded-sms-notification-form").submit(function () {
                    $('#ws-error-response, #ws-success-response').hide();
                    var url = '<?php echo $block->getAjaxUrl()?>';
                    var orderId = $("input[name='orderId']").val();
                    var phone = $("input[name='phone']").val();
                    var phonePrefix = $("#phonePrefix").val();
                    var countryCode = $("#countryCode").val();
                    var unsubscribe = '<?php echo $block->getUnsubscribeFlag()?>';

                    $.ajax({
                        url: url,
                        type: "POST",
                        data: {order: orderId, phone: phone, prefix: phonePrefix, country: countryCode, unsubscribe:unsubscribe},
                        showLoader: true,
                        success: function (response) {
                            if (response.success === true) {
                                $('#ws-error-response').hide();
                                $('#ws-success-response').show();
                            } else {
                                $('#ws-error-response').show();
                                $('#ws-error-response').html(response.error);
                            }
                        }
                    });
                    return false;
                });
            });
        });
    </script>
<?php endif; ?>