<?php if ($this->canShowEmbedded()): ?>
    <?php
        $order = $this->getOrderId() ? '?orderID=' . $this->getOrderId() : '';
        $platform = ($this->getOrderId() ? '&' : '?') . 'platformType=' . $this->getPlatform();
        $weSupplyTrackUrl = $this->getWeSupplyTrackUrl() . $order . $platform;
    ?>
    <div class="embedded-iframe-container">
        <iframe class="embedded-iframe" style="width: 100%;" width="100%" height="820" src="<?php echo $weSupplyTrackUrl ?>" frameborder="0" scrolling="no" allowfullscreen></iframe>
    </div>
<?php else: ?>
    <div class="not-found">
        <h1><?= /* @escapeNotVerified */ __('Shipment Tracking is currently disabled.') ?></h1>
        <div class="message">
            <p><?= /* @escapeNotVerified */ __('Please contact support.') ?></p>
        </div>
    </div>
<?php endif; ?>
