<?php
    /** @var $block WeSupply\Toolbox\Block\System\Config\SpecificEstimationRanges */
    /** @var WeSupply\Toolbox\Helper\Estimates $helper */
    $helper = $this->helper('WeSupply\Toolbox\Helper\Estimates');
    $availableShippingMethods = $helper->getAvailableShippingMethodsGroupedByCarriers();
?>

<table class="admin__control-table" cellpadding="10" cellspacing="0">
    <thead>
        <tr>
            <th><?= /* @escapeNotVerified */ __('Carrier/Method'); ?></th>
            <th><?= /* @escapeNotVerified */ __('Range'); ?></th>
            <th><?= /* @escapeNotVerified */ __('Additional Message'); ?></th>
            <th><?= /* @escapeNotVerified */ __('Hide ETA'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($availableShippingMethods as $carriers): ?>
            <tr>
                <td colspan="5">
                    <strong><?= /* @escapeNotVerified */ $this->htmlEscape($carriers['label']) ?></strong>
                </td>
            </tr>
            <?php foreach ($carriers['methods'] as $method): ?>
                <tr>
                    <?php $prefix = $method['code']; ?>
                    <?php $etaExcluded = $method['eta_excluded']; ?>
                    <td class="shipping-method">
                        <?php $label = $block->htmlEscape($method['label']); ?>
                        <?php $id = 'id="' . $prefix . '_shipping_method"'; ?>
                        <?php $name = 'name="groups[step_5][fields][estimation_range_specific][value][' . $prefix . '][shipping_method]"'; ?>
                        <?php $value = 'value="' . $prefix . '"'; ?>
                        <input type="hidden" <?= /* @escapeNotVerified */ $id ?> <?= /* @escapeNotVerified */ $name ?> <?= /* @escapeNotVerified */ $value ?>>
                        <?= /* @escapeNotVerified */ $label ?>
                    </td>
                    <td class="specific-range">
                        <?php $id = 'id="' . $prefix . '_specific_range"'; ?>
                        <?php $name = 'name="groups[step_5][fields][estimation_range_specific][value][' . $prefix . '][specific_range]"'; ?>
                        <?php $value = 'value="' . $helper->getEstimationRangeValue($prefix, 'specific_range') . '"'; ?>
                        <?php if ($etaExcluded): ?>
                            <span class="fake-input"></span>
                        <?php else: ?>
                            <input class="validate-number validate-zero-or-greater" type="text" <?= /* @escapeNotVerified */ $id ?> <?= /* @escapeNotVerified */ $name ?> <?= /* @escapeNotVerified */ $value ?>>
                        <?php endif ?>
                    </td>
                    <td class="additional-message">
                        <?php $id = 'id="' . $prefix . '_additional_message"'; ?>
                        <?php $name = 'name="groups[step_5][fields][estimation_range_specific][value][' . $prefix . '][additional_message]"'; ?>
                        <?php $value = 'value="' . $helper->getEstimationRangeValue($prefix, 'additional_message') . '"'; ?>
                        <input type="text" <?= /* @escapeNotVerified */ $id ?> <?= /* @escapeNotVerified */ $name ?> <?= /* @escapeNotVerified */ $value ?>>
                    </td>
                    <td class="hide-estimation">
                        <?php $id = 'id="' . $prefix . '_hide_estimation"'; ?>
                        <?php $name = 'name="groups[step_5][fields][estimation_range_specific][value][' . $prefix . '][hide_estimation]"'; ?>
                        <?php $isChecked = $helper->getEstimationRangeValue($prefix, 'hide_estimation', 'bool') ? 'checked="checked"' : ''; ?>
                        <?php if ($etaExcluded): ?>
                            <span class="fake-checkbox"></span>
                        <?php else: ?>
                            <input type="checkbox" <?= /* @escapeNotVerified */ $id ?> <?= /* @escapeNotVerified */ $name ?> <?= /* @escapeNotVerified */ $isChecked ?>>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>