<?php echo $block->getButtonHtml(); ?>

<?php  $helper = $this->helper('WeSupply\Toolbox\Helper\Data'); ?>
<span class="collect-indicator" id="testconnection_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="valid_message_span"></span>
    <span style="color:red" id="invalid_message_span">
        <?php if ($helper->getConnectionStatusByScope() === null): ?>
            <?= /* @escapeNotVerified */ __('Account credentials was not validated'); ?>
        <?php elseif ($helper->getConnectionStatusByScope() === 0): ?>
            <?= /* @escapeNotVerified */ __('Invalid account credentials'); ?>
        <?php endif; ?>
    </span>
</span>

<?php $allStores = $helper->getAllStores(); ?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'prototype'
    ], function($, alert){
        $(function () {

            var storesCount = '<?php echo count($allStores); ?>';
            if (storesCount > 1) {
                alert({
                    content: $.mage.__('Multiple Store Views detected.<br/><br/>If you want to sync each Store View to different WeSupply accounts, you\'ll need to configure all the settings from Step 1 and Step 2 per each Store View, with the specific account credentials.'),
                    actions: {
                        always: function(){}
                    }
                });
            }

            var collectSpan = $('#testconnection_span');
            var subdomain = $('#wesupply_api_step_2_wesupply_subdomain');
            var apiClientId = $('#wesupply_api_step_1_wesupply_client_id');
            var apiClientSecret = $('#wesupply_api_step_1_wesupply_client_secret');
            var connectionTest = $('#row_wesupply_api_step_1_wesupply_connection_test');

            apiClientId.add(apiClientSecret).on('keyup', function() {
                collectSpan.find('.collected').hide();
                $('#valid_message_span, #invalid_message_span').text('');
                connectionTest.find('.note').text('Please test and save your WeSupply credentials!');
            });


            $('#test_credentials').click(function () {
                new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                    parameters: {'subdomain': subdomain.val(), 'apiClientId': apiClientId.val(), 'apiClientSecret': apiClientSecret.val()},
                    loaderArea: false,
                    asynchronous: true,
                    onCreate: function () {
                        collectSpan.find('.collected').hide();
                        collectSpan.find('.processing').show();
                        $('#valid_message_span, #invalid_message_span').text('');
                    },
                    onSuccess: function (response) {
                        collectSpan.find('.processing').hide();

                        if (response.status > 200) {
                            $('#invalid_message_span').show().text('Something went wrong.');
                        } else {
                            if (response.responseJSON.success === false) {
                                $('#invalid_message_span').text(response.responseJSON.message);
                            } else {
                                collectSpan.find('.collected').show();
                                $('#valid_message_span').text(response.responseJSON.message);
                            }
                        }
                    }
                });
            });
        });
    });
</script>