<?php
    /** @var  $block WeSupply\Toolbox\Block\System\Config\AccessKey */
    $block = $this->getLayout()->createBlock('WeSupply\Toolbox\Block\System\Config\AccessKey');
?>

<a id="regenerate_link" class="button-type <?php echo !$block->isVisible() ? 'disabled' : ''; ?>" href="javascript:void(0)"><?php echo __('Regenerate'); ?></a>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'prototype'
    ], function($, confirmation)
    {
        $('#regenerate_link').on('click', function ()
        {
            var regenerateLink = $(this),
                currentVal = $('#wesupply_api_integration_access_key').val();

            if (!regenerateLink.hasClass('disabled') && currentVal !== '') {
                var contentHtml  = '<p>' + $.mage.__('Are you sure you want to regenerate the <strong>AccessKey?</strong>') + '</p>';
                    contentHtml += '<p>' + $.mage.__('The connection to your WeSupply Platform will be lost.') + '</p>';
                    contentHtml += '<p>' + $.mage.__('You will have to reconnect it using the newly generated <strong>AccessKey</strong> otherwise, the orders sync and other WeSupply functionalities will no longer work.') + '</p>';
                confirmation({
                    title: $.mage.__('Regenerate AccessKey'),
                    content: contentHtml,
                    actions: {
                        confirm: function(){
                            regenerate(regenerateLink);
                        }
                    },
                    buttons: [{
                        text: $.mage.__('Cancel'),
                        class: 'action-secondary action-dismiss',
                        click: function (event) {
                            this.closeModal(event);
                        }
                    }, {
                        text: $.mage.__('It\'s OK, Regenerate now'),
                        class: 'action-primary action-accept',
                        click: function (event) {
                            this.closeModal(event, true);
                        }
                    }]
                });
            }

            if (currentVal === '') {
                regenerate(regenerateLink);
            }
        });

        $('#wesupply_api_integration_access_key_inherit').on('click', function() {
            $('.copy-text').removeClass('disabled').prop('disabled', false); // always enabled
            if ($(this).is(':checked')) {
                $('#regenerate_link').addClass('disabled');
            } else {
                $('#regenerate_link').removeClass('disabled');
            }
        });

        function regenerate(regenerateLink)
        {
            new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
                parameters:     {},
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    regenerateLink.text('<?php echo __('Generating...') ?>').addClass('disabled');
                },
                onSuccess: function(response) {
                    regenerateLink.text('<?php echo __('Saving...') ?>');
                    regenerateLink.parent().find('.note').html('<span class="saving_message_span"><?php echo __('Saving configuration. Please wait...') ?></span>');

                    $('#wesupply_api_integration_access_key')
                        .prop('readonly', false)
                        .prop('disabled', false)
                        .val(response.responseJSON.accesskey);

                    if ($('#save').length > 0 ) {
                        setTimeout(function () {
                            $('#save').click();
                            $('#wesupply_api_integration_access_key')
                                .prop('readonly', true)
                                .prop('disabled', true);
                        }, 500);
                    } else {
                        alert('Make sure to Save credentials after generation');
                    }
                }
            });
        }
    });
</script>