<?php /** @var block WeSupply\Toolbox\Block\System\Config\StoreIdsList */ ?>
<div class="stores-list">
    <table cellpadding="10" cellspacing="0">
        <thead>
            <td width="10%"><strong>ID</strong></td>
            <td width="30%"><strong>Website</strong></td>
            <td width="30%"><strong>Store</strong></td>
            <td><strong>StoreView</strong></td>
        </thead>
        <?php
            $websites = $block->getWebsites();
            foreach ($websites as $website) {
                $websiteName = $block->htmlEscape($website->getName());
                $groups = $website->getGroups();
                foreach ($groups as $group) {
                    $storeName = $block->htmlEscape($group->getName());
                    $stores = $group->getStores();
                    foreach ($stores as $storeView) {
                        ?><tr>
                            <td width="10%"><?php echo $storeView->getId(); ?></td>
                            <td width="30%"><?php echo $websiteName;?></td>
                            <td width="30%"><?php echo $storeName;?></td>
                            <td><?php echo  $block->htmlEscape($storeView->getName()); ?></td>
                        </tr><?php

                    }
                }
            }
    ?>
    </table>
</div>