<?php
    $currentVersion = $this->getCurrentVersion();
    $versionCompare = $this->compareVersion();
?>
<div class="integration-header">
    <p>
        <?php echo __('Proactive Package Tracking, Notifications, Store Locator, Returns and RMA, CSAT & NPM, Delivery Estimate - all integrated with Magento 2 and providing the best post-purchase customer experience.') ?>
        <span class="bold"><?php echo __('Before starting the configuration, make sure to first create a <a href="%1" target="_blank">WeSupply Account HERE</a>.', $this->getWeSupplyUrl()) ?></span>
    <p>
    <?php if (!$currentVersion): ?>
        <p>
            <?php echo __('Cannot read module version. Please update your extension.') ?>
            <a href="<?php echo $this->getDownloadLink(); ?>" title="<?php echo __('Download latest version.'); ?>">
                <?php echo __('Download latest version.'); ?>
            </a>
        </p>
    <?php else: ?>
        <?php if ($versionCompare): ?>
            <p class="<?php echo $versionCompare === 'diff' ? 'old-version' : ''; ?>">
                <?php echo __('Currently installed version:') ?> <?php echo $this->getCurrentVersion(); ?>.
                <?php if ($versionCompare === 'diff'): ?>
                    <?php echo __('Available version: ') ?> <?php echo $this->getModuleLatestVersion() ?>.
                    <?php echo __('Please update your extension.'); ?>
                    <a href="<?php echo $this->getDownloadLink(); ?>" title="<?php echo __('Download from here.'); ?>">
                        <?php echo __('Download from here.'); ?>
                    </a>
                <?php else: ?>
                    <?php echo __('Good Job! You are up to date.'); ?>
                <?php endif; ?>
            </p>
        <?php else: ?>
            <p>
                <?php echo __('Currently installed version:') ?> <?php echo $this->getCurrentVersion(); ?>.
                <?php echo __('Unable to check latest module version.') ?>
            </p>
        <?php endif; ?>
    <?php endif; ?>
</div>