<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
  $product = $block->getSaleableItem();
  $rrp = $product->getResource()->getAttribute('c2c_rrp')->getFrontend()->getValue($product);
  $saveRRP = $rrp;
  $savePrice = $block->getDisplayValue();
  $savePrice2 = $savePrice;
  $priceSaving = $saveRRP - $savePrice2;
  $rrp_label = ($block->getPriceType() == 'oldPrice') ? 'Special Offer' : 'RRP' ;
  $price_label = ($block->getPriceType() == 'oldPrice') ? 'Normal Price:' : 'Offer Price' ;
?>
<?php if (!empty($rrp) && $rrp > $savePrice && $priceSaving > 0): ?>
<?php $percentSaving = ($priceSaving / $saveRRP) * 100; ?>
<?php endif; ?>
<?php if (!empty($rrp) && $rrp > $savePrice): ?>
<?php if($rrp_label=="Special Offer"){ ?>
<div class="recommended-price"><strong><?php echo $rrp_label; ?></strong> <!-- &pound;<span class="recommended-price-price"><?php echo number_format($rrp, 2) ?></span> --></div>
<?php } else{ ?>  
<div class="recommended-price"><?php echo $rrp_label; ?>: &pound;<span class="recommended-price-price"><?php echo number_format($rrp, 2) ?></span></div>
<?php } ?>
<?php endif; ?>
<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */ ?>
<span class="price-container <?= /* @escapeNotVerified */ $block->getAdjustmentCssClasses() ?>"
        <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
    <?php if ($block->getDisplayLabel()): ?>
          <?php if($price_label!="Offer Price") { ?>
        <span class="price-label"><?= /* @escapeNotVerified */ $price_label ?></span>
          <?php } ?>
    <?php endif; ?>
    <span <?php if ($block->getPriceId()): ?> id="<?= /* @escapeNotVerified */ $block->getPriceId() ?>"<?php endif;?>
        <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
        data-price-amount="<?= /* @escapeNotVerified */ $block->getDisplayValue() ?>"
        data-price-type="<?= /* @escapeNotVerified */ $block->getPriceType() ?>"
        class="price-wrapper <?= /* @escapeNotVerified */ $block->getPriceWrapperCss() ?>"
    ><?= /* @escapeNotVerified */ $block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()) ?></span>
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?= $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="price" content="<?= /* @escapeNotVerified */ $block->getDisplayValue() ?>" />
        <meta itemprop="priceCurrency" content="<?= /* @escapeNotVerified */ $block->getDisplayCurrencyCode() ?>" />
    <?php endif; ?>
</span>
<?php if (!empty($rrp) && $rrp > $savePrice && $priceSaving > 0): ?>
<div class="save-price">You Save: <span>&pound;<?php echo number_format($priceSaving, 2, '.', ' ') ?> (<?php echo number_format($percentSaving, 0, '.', ' ') ?>%)</span></div>
<?php endif; ?>