<script>
    require(['jquery', 'iframeResizer' ],
        function ($) {
            $(function () {
                waitUntilExists(function() { return $('.embedded-iframe').length; }, function() {
                    var iframe = $('.embedded-iframe'),
                        headerHeight = $('header').outerHeight(),
                        windowHeight = $(window).innerHeight(),
                        availableHeight =  windowHeight - headerHeight - 70,
                        isOldIE = (navigator.userAgent.indexOf("MSIE") !== -1);
                    iframe.css({'height': availableHeight + 'px'});

                    iframe.on('load', function(){
                        iFrameResize({
                            log: false,
                            minHeight: availableHeight,
                            resizeFrom: 'parent',
                            scrolling: true,
                            inPageLinks: true,
                            autoResize: true,
                            heightCalculationMethod: isOldIE ? 'max' : 'bodyScroll',
                            onInit: function(iframe) {
                                iframe.style.height = availableHeight + 'px';
                            },
                            onResized: function(messageData) {
                                setTimeout(function() {
                                    messageData.iframe.style.visibility = 'visible';
                                }, 300);
                            },
                            onMessage: function(messageData) {
                                if (history.pushState && messageData.message.hasOwnProperty('trackNo')) {
                                    var newUrl = window.location.protocol + '//' + window.location.host + window.location.pathname.replace(/\/$/, '') + '/' + messageData.message.trackNo;
                                    window.history.pushState({path:newUrl}, '', newUrl);
                                }
                            }
                        }, '.embedded-iframe');
                    });

                }, function() { });
                function waitUntilExists(isReady, success, error, count, interval){
                    if (count === undefined) {
                        count = 300;
                    }
                    if (interval === undefined) {
                        interval = 20;
                    }
                    if (isReady()) {
                        success();
                        return;
                    }
                    setTimeout(function(){
                        if (!count) {
                            if (error !== undefined) {
                                error();
                            }
                        } else {
                            waitUntilExists(isReady, success, error, count -1, interval);
                        }
                    }, interval);
                }
            });
        });
</script>
