<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?= /* @escapeNotVerified */ __('Thank you for your order. We\'ll email you an order confirmation with a summary of your order.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>



<?php
$orderId = $block->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$collection = $objectManager->create('Magento\Sales\Model\Order'); 
$order = $collection->loadByIncrementId($orderId);
$orderId = $order ->getId();

//$order = $objectManager->create('Magento\Sales\Api\Data\OrderInterface')->load($orderId);

$total = (float)number_format($order->getSubtotal(),2);
?>

<!-- Event snippet for Purchase/Sale conversion page -->
<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-1045431775/p-YyCLfEXhDfi8DyAw',
      'value': <?php echo $total; ?>,
      'currency': 'GBP',
      'transaction_id': '<?php echo $orderId; ?>'
  });
</script>
<!-- ************ Google Adwords Purchase End ****************** -->

<!-- ************ Google Adwords Visitors to checkout Page Remarketing List Start ************ -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = '1045431775';
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "PpsvCP2V1wIQ34vA8gM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/1045431775/?label=PpsvCP2V1wIQ34vA8gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- ************ Google Adwords Visitors to checkout Page Remarketing List End ************ -->

<?php 


$_products = $order->getAllItems();
 
$_totalData = $order->getData();


$_grand = $_totalData['grand_total']; 
$_sub = $_totalData['subtotal']; 
$_ship = $_totalData['shipping_amount']; 
$_discount = $_totalData['discount_amount'];
$_voucher = $_totalData['coupon_code'];
$_total = $_sub + $_discount;
?>
 <?php 
 //$outputMessage = Mage::getSingleton('core/session')->getOriginalRefererUrl();
 $outputMessage = $_SERVER["HTTP_REFERER"];
    if (strpos($outputMessage,'TradeTracker') !== false): ?>
             <!-- ************ Start TradeTracker code ************ --> 
                <img src="http://www.keengardener.co.uk/garden/conversion.php?campaignID=8412&productID=12761&conversionType=sales&https=1&transactionID=<?php echo $block->getOrderId(); ?>&transactionAmount=<?php echo $_total; ?>&email=&descrMerchant=<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getName() . ',';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>&descrAffiliate=<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getName() . ',';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>" width="1" height="1" border="0" alt="" />
            <!-- ************ End TradeTracker code ************ --> 
<?php endif; ?>

 <?php 
 //$outputMessage = Mage::getSingleton('core/session')->getOriginalRefererUrl();
 $outputMessage = $_SERVER["HTTP_REFERER"];
    if (strpos($outputMessage,'AffiliateFuture') !== false): ?>
             <!-- ************ Start AffiliateFuture Tracking Code--> 
            <script language="javascript" src="https://scripts.affiliatefuture.com/AFFunctions.js"></script>
            <script language="javascript">

                            var merchantID = 5683;
                            var orderValue = '<?php echo $_total; ?>';
                            var orderRef = '<?php echo $block->getOrderId(); ?>';
                            var payoutCodes = '<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getSku() . ',' . ($p->getPrice() * $p->getQtyOrdered()) . ',';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>';
                            var offlineCode = '';
                            var voucher = '';
                            var products = '';
                            var curr = '';

                            AFProcessSaleV5(merchantID,orderValue,orderRef,payoutCodes,offlineCode,voucher,products,curr);
            </script>
            <!-- ************ End AffiliateFuture tracking code ************ -->
<?php endif; ?>

 <?php 
 //$outputMessage = Mage::getSingleton('core/session')->getOriginalRefererUrl();
 $outputMessage = $_SERVER["HTTP_REFERER"];
    if (strpos($outputMessage,'Aff1liateFuture') !== false): ?>
             <!-- ************ Start AffiliateFuture Tracking Code --> 
            <script language="javascript" src="https://scripts.affiliatefuture.com/AFFunctions.js"></script>
            <script language="javascript">

                            var merchantID = 5683;
                            var orderValue = '<?php echo $_total; ?>';
                            var orderRef = '<?php echo $block->getOrderId(); ?>';
                            var payoutCodes = '<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getSku() . ',' . ($p->getPrice() * $p->getQtyOrdered()) . ',';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>';
                            var offlineCode = '';
                            var voucher = '';
                            var products = '';
                            var curr = '';

                            AFProcessSaleV5(merchantID,orderValue,orderRef,payoutCodes,offlineCode,voucher,products,curr);
            </script>
            <!-- ************ End AffiliateFuture tracking code ************ -->
<?php endif; ?>


 <?php 
 //$outputMessage = Mage::getSingleton('core/session')->getOriginalRefererUrl();
 $outputMessage = $_SERVER["HTTP_REFERER"];
    if (strpos($outputMessage,'Webgains') !== false): ?>
            <!-- ************ Start Webgains Tracking Code if original url = 'Webgains' ************ --> 
            <!-- OLD WEBGAINS CODE KEEP IN PLACE 060319-->
                <script language="javascript" type="text/javascript">

                var wgOrderReference = "<?php echo $block->getOrderId(); ?>";
                var wgOrderValue = "<?php echo $_total; ?>";
                var wgEventID = "6385";
                var wgComment = "";
                var wgLang = "en_EN";
                var wgsLang = "javascript-client";
                var wgVersion = "1.2";
                var wgProgramID = 4007;
                var wgSubDomain = "track";
                var wgCheckSum = "";
                var wgItems = "<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getSku() . '|';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>";
                var wgVoucherCode = "<?php echo $_voucher; ?>";
                var wgCustomerID = "<?php echo $block->getOrderId(); ?>";

                if(location.protocol.toLowerCase() == "https:") wgProtocol="https";
                else wgProtocol = "http";
                wgUri = wgProtocol + "://" + wgSubDomain + ".webgains.com/transaction.html" + "?wgver=" + wgVersion + "&wgprotocol=" + wgProtocol + "&wgsubdomain=" + wgSubDomain + "&wgslang=" + wgsLang + "&wglang=" + wgLang + "&wgprogramid=" + wgProgramID + "&wgeventid=" + wgEventID + "&wgvalue=" + wgOrderValue + "&wgchecksum=" + wgCheckSum + "&wgorderreference="  + wgOrderReference + "&wgcomment=" + escape(wgComment) + "&wglocation=" + escape(document.referrer) + "&wgitems=" + escape(wgItems) + "&wgcustomerid=" + escape(wgCustomerID) + "&wgvouchercode=" + escape(wgVoucherCode);

                document.write('<sc'+'ript language="JavaScript"  type="text/javascript" src="'+wgUri+'"></sc'+'ript>');
                </script>
                <noscript>

                <img src="http://track.webgains.com/transaction.html?wgver=1.2&wgprogramid=4007&wgrs=1&wgvalue=<?php echo $_total; ?>&wgeventid=6385&wgorderreference=<?php echo $block->getOrderId(); ?>&wgitems=<?php 
            $productLines = array();
            foreach($_products as $product => $p) {
                if ($p['order_id'] == $lastOrderId) {
                    if (is_null($p['parent_item_id'])) {
                        $productLines[$p['item_id']] = $p->getSku() . '|';
                    }
                }
            }
            foreach ($productLines as $productLine) {
                echo $productLine;
            }
            ?>&wgvouchercode=<?php echo $_voucher; ?>&wgcustomerid=<?php echo $block->getOrderId(); ?>" alt="" />

                </noscript>
            <!-- OLD WEBGAINS CODE KEEP IN PLACE 060319-->
            <!-- NEW WEBGAINS CODE 060319-->
            <script>
                 (function(w,e,b,g,a,i,n,s){w['ITCVROBJ']=a;w[a]=w[a]||function(){
                    (w[a].q=w[a].q||[]).push(arguments)},w[a].l=1*new Date();i=e.createElement(b),
                    n=e.getElementsByTagName(b)[0];i.async=1;i.src=g;n.parentNode.insertBefore(i,n)
                })(window,document,'script','https://analytics.webgains.io/cvr.min.js','ITCVRQ');
                ITCVRQ('set', 'trk.programId', '4007');
                ITCVRQ('set', 'cvr', {
                    value: "<?php echo $_total; ?>",
                    currency: 'GBP',
                    language: 'en_EN',
                    eventId: '6385',
                    orderReference : '<?php echo $block->getOrderId(); ?>',
                    comment: '',
                    multiple: '',
                    checksum: '',
                    items: '<?php 
                        $productLines = array();
                        foreach($_products as $product => $p) {
                            if ($p['order_id'] == $lastOrderId) {
                                if (is_null($p['parent_item_id'])) {
                                    $productLines[$p['item_id']] = $p->getSku() . '|';
                                }
                            }
                        }
                        foreach ($productLines as $productLine) {
                            echo $productLine;
                        }
                        ?>',
                    customerId: '',
                    voucherId: '<?php echo $_voucher; ?>'
                });
                ITCVRQ('conversion');
            </script>           
            <!-- NEW WEBGAINS CODE 060319-->
            <!-- ************ End Webgains Tracking Code ************ --> 
<?php endif; ?>
<!-- ************ START GOOGLE CERTIFIED SHOPS ************ --> 
<?php
    $orderId = $block->getOrderId();
    //$customer = Mage::getModel('customer/customer')->load($order->getCustomerId());
    $customer = $objectManager->create('Magento\Customer\Model\Customer')->load($order->getCustomerId());

    $address = $order->getShippingAddress();
    $backorder = false; // some backorder logic
    $shipDate = new Zend_Date(); // some logic to determine ship date
    ?>

    <!-- START Google Certified Shops Order -->
    <div id="gts-order" style="display:none;" translate="no">

      <!-- start order and merchant information -->
      <span id="gts-o-id"><?php echo $block->getOrderId(); ?></span>
      <!--to fix --><span id="gts-o-email"><?php echo htmlentities($customer->getEmail()); ?></span>
      <span id="gts-o-country">GB</span>
      <span id="gts-o-currency">GBP</span>
      <span id="gts-o-total"><?php echo $_total; ?></span>
      <span id="gts-o-discounts"><?php echo $order->getDiscountAmount(); ?></span>
      <span id="gts-o-shipping-total"><?php echo $order->getShippingAmount(); ?></span>
      <span id="gts-o-tax-total"><?php echo $order->getTaxAmount(); ?></span>
      <!--to fix --><span id="gts-o-est-ship-date">ORDER_EST_SHIP_DATE</span>
      <!--to fix --><span id="gts-o-est-delivery-date">ORDER_EST_DELIVERY_DATE</span>
      <!--to fix --><span id="gts-o-has-preorder">TO_DO</span>
      <span id="gts-o-has-digital">N</span>
      <!-- end order and merchant information -->

      <!-- start repeated item specific information -->
      <!-- item example: this area repeated for each item in the order -->
      <?php foreach ($order->getAllItems() as $item): ?>
      <?php $_product = $this->getProduct(); ?>
      <span class="gts-item">
        <span class="gts-i-name"><?php echo htmlentities($item->getName()); ?></span>
        <span class="gts-i-price"><?php echo $item->getBasePrice(); ?></span>
        <span class="gts-i-quantity"><?php echo (int)$item->getQtyOrdered(); ?></span>
        <span class="gts-i-prodsearch-id"><?php echo $item->getSku(); ?></span>
        <span class="gts-i-prodsearch-store-id">752221</span>
      </span>
      <?php endforeach; ?>
      <!-- end item 1 example -->
      <!-- end repeated item specific information -->

    </div>
    <!-- END Google Certified Shops Order -->           
<!-- ************ END GOOGLE CERTIFIED SHOPS ************ --> 

