<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$qty = $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$stock_threshold_qty = $config->getConfigValue('cataloginventory/options/stock_threshold_qty');

if($qty < $stock_threshold_qty && $qty != 0)
{
    echo '<div class="availability only">Only ' . $qty . ' left in stock</div>';
}
?>
<!--
<?php //if ($block->displayProductStockStatus()): ?>
    <?php //if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ //echo __('Availability') ?>">
            <span class="label"><?php /* @escapeNotVerified */ //echo __('Availability:') ?></span>
            <span><?php /* @escapeNotVerified */ //echo __('In stock') ?></span>
        </div>
    <?php //else: ?>
        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ //echo __('Availability') ?>">
        	<span class="label"><?php /* @escapeNotVerified */ //echo __('Availability:') ?></span>
            <span><?php /* @escapeNotVerified */ //echo __('Out of stock') ?></span>
        </div>
    <?php //endif; ?>
<?php //endif; ?>
-->
