<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order) : ?>
    <?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
    <?php if ($trackCollection) : ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <?php if ($block->escapeHtml($_item->getTitle()) == 'DPD') {
                        $tracking_url = 'https://track.dpd.co.uk/parcels/1550'.($block->escapeHtml($_item->getNumber()*19539));
                    }elseif ($block->escapeHtml($_item->getTitle()) == 'Royal Mail Tracked 48') {
                        $tracking_url = 'https://www.royalmail.com/track-your-item#/tracking-results/'.$block->escapeHtml($_item->getNumber());
                    }elseif ($block->escapeHtml($_item->getTitle()) == 'The Pallet Network') {
                        $tracking_url = 'http://www.tpnconnect.com/Tracking';
                    }else{
                        $tracking_url = '#';
                    } ?>
                    <td>
                        <a href="<?= $tracking_url; ?>" target="_blank">
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
